[package]
name = "payout_contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
concordium-std = "10.0"

[features]
default = ["std"]
std = ["concordium-std/std"]
